# Generated by Django 5.0.6 on 2024-10-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'Condition'},
        ),
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
