# Generated by Django 5.0.6 on 2024-10-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
