# Generated by Django 5.0.6 on 2024-10-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(),
        ),
    ]
