# Generated by Django 5.0.6 on 2024-10-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.FloatField(),
        ),
    ]
