# Generated by Django 5.0.6 on 2024-10-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(),
        ),
    ]
