# Generated by Django 5.0.6 on 2024-10-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
