# Generated by Django 5.0.6 on 2024-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.CharField(help_text='Enter Image Link', max_length=1000),
        ),
    ]
